### PR TITLE
Enable tcmalloc for additional memory management

### PR DESCRIPTION
**Pull request by unclesamwk**

### CODE REVIEW

**Comment by dkorittki** [comment]
@unclesamwk Can you give a little description on what tcmalloc is useful for in context of this formula?

**Comment by Takios** [comment]
I would prefer to have a seperate tcmalloc formula instead of bloating the percona formula for this.

**Comment by janhorstmann** [comment]
> I would prefer to have a seperate tcmalloc formula instead of bloating the percona formula for this.

We would lose the possibility to interactively restart the mysql service. But we would not do that anyway. So I believe using a separate formula would indeed be the best solution.

**Comment by Takios** [comment]
Because of the reasons in earlier comments, I'm closing this PR.

**Pull request closed without merging**
